#! /usr/bin/Rscript

#######################################################################################
### Run-c2g.R - V0.1 - Clement Goubert (2020) - goubert.clement@gmail.com           ###
### ------------------------------------------------------------------------------- ###
### This script uses the R function consensus2genome to infer breakpoints           ###
### to split and/or trim TE                                                         ###
### consensi generated by tools like RepeatModeler2, EDTA, REPET,...                ###
### USAGE:  TE-slocer.sh <TE-header> <[>                                            ###                            ###
### query: path to query (fasta file)                                               ###
### db: path to blast db (blast formated nucleotide database)                       ###
#######################################################################################

source("consensus2genome.R")

Args = commandArgs()
input=as.character(Args[6])
database=as.character(Args[7])
print(input)
pdf(width = 8, height = 4, file = paste(tail(strsplit(as.character(input), "/")[[1]],1), ".c2g.pdf", sep=""))
consensus2genome(query = input,
                 db = database)
dev.off()